# Generated by Django 3.2.8 on 2021-10-12 21:36

from django.db import migrations

def forwards_func(apps, schema_editor):
    Teacher = apps.get_model("teachers", "Teacher")
    db_alias = schema_editor.connection.alias

    Teacher.objects.using(db_alias).bulk_create([
        Teacher(name='Vinny Yasa'),
        Teacher(name='Ashley Tanga'),
        Teacher(name='Anne Usara'),
        Teacher(name='Vick Rum'),
        Teacher(name='Mindy Fuller'),
    ])

def reverse_func(apps, schema_editor):
    Teacher = apps.get_model("teachers", "Teacher")
    db_alias = schema_editor.connection.alias
    Teacher.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]