# Generated by Django 3.2.8 on 2021-10-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_auto_20211012_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(1, 'Program'), (2, 'Barre'), (3, 'Class'), (4, 'Pilates'), (5, 'Tai Chi'), (6, 'Vinyasa')], default=3, verbose_name='Class instruction type')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('duration', models.IntegerField(verbose_name='Duration (minutes)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
